### ISSUE TITLE
Manage empty params

### ISSUE THREAD

**Issue by aurrelhebert** [cityzendata/warp10-quantumviz#13]

**Comment by LostInBrittany** [comment]
Today there are 4 types of valid response formats for Quantumviz:

- A single GTS (in standard GTS JSON format)
- A list of GTS
- An object with a single GTS and a single params object
  ```json
{
  gts: { ... },
  params: {...} 

}
  ```
- An object with a gts list and a params list
```json
{
  gts: [ { ... }, ...]
  params: [ {...}, ...] 
}
``` 

Right now the global params can only be added to the last two formats.

Going to modify the last two formats to make the params optional.
