### ISSUE TITLE
Read / import mc2 from url in order to execute it by the widget

### ISSUE THREAD

**Issue by slambour** [cityzendata/warp10-quantumviz#4]
Read / import mc2 from url in order to execute it by the widget (geoquantumviz for example).
In this case, you case edit the mc2 file locally (with any editor) and execute it inside the widget without copy/paste (with all error that <ctrl+c><ctrl+v> implies...)

**Comment by LostInBrittany** [comment]
It's done in the last release of [Quantum](https://github.com/cityzendata/warp10-quantum/)
