### ISSUE TITLE
Too many requests 

### ISSUE THREAD

**Issue by slambour** [cityzendata/warp10-quantumviz#7]
Loading warp10-quantumviz.html implies more than 40 http requests with a global size of 411kb 

please Tree-shake and vulcanize components.
Tested with 1.1.10.0 version

**Comment by LostInBrittany** [comment]
It won't work, as it would kill interoperability.

Right now these repository is a collection of widgets, not an application.
If I vulcanize I force either to load ask the widgets (one big file
vulcanized) or to choose only one widget (by creatibg vulcanized subsets),
as you could not use two different, non-0-intersention subsets in the same
page.

As for any polymer/web component application, it's to the end application
to do the vulcanize (as quantum does), not to the component catalog.
